<?php

namespace Database\Seeders;

use App\Models\Listing;
use App\Models\ListingImage;
use App\Models\Tag;
use Illuminate\Database\Seeder;

class ListingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $possibleTitles = $this->getTitles();

        $listings = collect(range(1, 100))->map(fn ($i) => Listing::factory()
            ->has(ListingImage::factory(rand(1, 3)), 'images')
            ->create([
                'title' => $possibleTitles[$i],
            ]));

        // Get a list of tags from the database
        $tags = Tag::query()->get();

        // Add some tags to listings
        $listings->each(function (Listing $listing) use ($tags) {
            $listing->tags()->attach(
                $tags->random(rand(1, 5))
            );
        });
    }

    public function getTitles(): array
    {
        return [
            "Men's Classic Blue Jeans",
            'Wireless Bluetooth Headphones',
            'Modern Leather Sofa',
            'Smart LED TV - 55 inch',
            'Stainless Steel Refrigerator',
            'Bestselling Mystery Novel',
            'Luxury Skincare Set',
            'Educational Building Blocks',
            'Professional Basketball Hoop',
            'Fitness Tracker Watch',
            'Diamond Solitaire Necklace',
            'Fashionable Sunglasses',
            'Laptop Backpack with USB Charging',
            'Home Office Desk',
            'Organic Superfood Powder',
            'Indoor Plant Collection',
            'Stainless Steel Cookware Set',
            'Gourmet Coffee Blend',
            'Colorful Office Supplies Set',
            'DIY Craft Kit',
            'Abstract Canvas Art',
            'Wireless Gaming Mouse',
            'Pet Grooming Kit',
            'Car Care Essentials Kit',
            'Baby Stroller with Adjustable Handle',
            'Outdoor Adventure Tent',
            'Yoga Mat and Accessories',
            'Vintage Vinyl Records Collection',
            'Smartphone Car Mount',
            'Designer Handmade Jewelry',
            'Handcrafted Wooden Puzzle',
            'Portable Espresso Maker',
            'Musical Keyboard for Beginners',
            'High-Performance Running Shoes',
            "Minimalist Men's Watch",
            'Interactive Video Game Console',
            'Board Game Collection',
            'Professional DSLR Camera',
            'Artistic Photography Book',
            'Smart Thermostat',
            'Premium Leather Wallet',
            'Elegant Party Dress',
            "Slim Fit Men's Suit",
            'Compact Electric Drill',
            'Gourmet Chocolate Assortment',
            'Bluetooth Portable Speaker',
            'Laptop Cooling Pad',
            'Organic Baby Food Sampler',
            'Deluxe Party Decorations Set',
            'Stainless Steel Water Bottle',
            'Cooking Class Experience',
            'Luxury Bath Towel Set',
            'Fragrance Gift Set for Him',
            'Complete Skincare Routine Kit',
            'Wireless Charging Pad',
            'Noise-Canceling Earbuds',
            'High-Quality Paint Set',
            'Outdoor Adventure Backpack',
            'Fly Fishing Rod and Reel Combo',
            'Hiking Gear Bundle',
            'Designer Swimwear',
            'Gourmet BBQ Spice Set',
            'Fashionable Crossbody Bag',
            "Chic Women's Boots",
            'Elegant Diamond Earrings',
            'Cozy Knit Scarf',
            'Designer Leather Belt',
            'Gourmet Tea Sampler',
            'Premium Quality Blanket',
            'Aromatherapy Candles Set',
            'Modern Wall Clock',
            'Sculptural Art Piece',
            "Professional Chef's Knife",
            'Baking Essentials Kit',
            'Luxury Bedding Collection',
            'Gaming Console Controller',
            'Classic Wooden Chess Set',
            'Stylish Laptop Sleeve',
            'Educational Science Kit',
            'Smartphone Camera Lens Kit',
            'Indoor Herb Garden Kit',
            'Classic Record Player',
            'Wireless Bluetooth Speaker',
            'Sleek Office Desk Lamp',
            "Designer Men's Cologne",
            'Luxury Silk Necktie',
            "Chic Women's Watch",
            'Creative DIY Painting Kit',
            'Yoga and Meditation Set',
            'Vintage Film Camera',
            'Adjustable Dumbbell Set',
            'Professional Makeup Kit',
            'Smart Home Security Camera',
            'Handcrafted Ceramic Mug Set',
            'Minimalist Wall Art Print',
            'Gourmet Olive Oil Sampler',
            'Stylish Canvas Tote Bag',
            'Interactive Learning Tablet',
            "Designer Women's Perfume",
            'Premium Leather Journal',
            'Fitness Resistance Bands Set',
            'Sleek Wireless Keyboard',
            'Digital Piano with Stand',
            "Men's Active Sportswear",
            "Stylish Men's Backpack",
            'Eco-Friendly Reusable Water Bottle',
            'Outdoor Camping Cookware Set',
            'Gourmet Cheese Selection',
            "Chic Women's Sandals",
            'Professional Photography Lighting Kit',
            'Luxury Bathrobe Set',
            'Woodworking Tools Collection',
            'Premium Chocolate Truffle Assortment',
            'Portable Solar Charger',
            'Smart Home Voice Assistant',
            'Modern Wall Art Sculpture',
            "Stylish Men's Wallet",
            "Elegant Women's Bracelet",
            'Creative DIY Candle Making Kit',
            'Yoga and Fitness Mat',
            'Retro Polaroid Camera',
            'Complete Home Gym Set',
            'Professional Makeup Brushes Set',
            'Wireless Smart Doorbell',
            'Hand-Painted Ceramic Dinnerware Set',
            'Abstract Geometric Wall Print',
            'Gourmet Wine and Cheese Pairing',
            "Chic Women's Sneakers",
            'Professional Video Camera',
            'Luxury Silk Scarf',
            'Outdoor Camping Tent',
            'High-Quality Woodworking Bench',
            'Premium Tea Infuser Set',
            'Stylish Laptop Messenger Bag',
            'Educational Space Exploration Kit',
            "Designer Men's Watch",
            'Fitness Exercise Ball',
            'Sleek Smartphone Wallet Case',
            'Digital Drawing Tablet',
            "Men's Classic Leather Belt",
            'Gourmet Artisanal Chocolate Bars',
            'Wireless Noise-Canceling Headphones',
            'Indoor Plant Care Kit',
            'Gourmet Coffee Grinder',
            'Creative DIY Pottery Kit',
            'Yoga and Meditation Cushion',
            'Vintage Retro Record Player',
            'Complete Dumbbell Weight Set',
            'Professional Makeup Vanity Mirror',
            'Smart Home Smart Plug',
            'Modern Sculptural Decor Piece',
            "Stylish Women's Clutch",
            "Elegant Men's Tie",
            'Sustainable Eco-Friendly Bag',
            'Retro Arcade Gaming Console',
            "Professional Chef's Cookware Set",
            'Luxury Scented Candle Collection',
            'Outdoor Adventure Hammock',
            'High-Quality Woodworking Tools Set',
            'Premium Loose Leaf Tea Collection',
            'Stylish Laptop Backpack',
            'Educational Robotics Kit',
            "Designer Women's Watch",
            'Fitness Resistance Band Set',
            'Sleek Wireless Earbuds',
            'Digital Sketching Pen',
            "Men's Fashionable Belt",
            'Artisanal Dark Chocolate Sampler',
            'Wireless In-Ear Headphones',
            'Indoor Plant Pot Set',
            'Gourmet Coffee Maker',
            'Creative DIY Knitting Kit',
            'Yoga and Meditation Blanket',
            'Vintage Film Camera Kit',
            'Complete Home Exercise Set',
            'Professional Makeup Organizer',
            'Smart Home Color-Changing Lights',
            'Modern Abstract Wall Painting',
            "Stylish Men's Messenger Bag",
            "Elegant Women's Necklace",
            'Sustainable Bamboo Cutlery Set',
            'Retro Handheld Gaming Device',
            "Professional Chef's Knife Set",
            'Luxury Fragrance Diffuser',
            'Outdoor Adventure Backpacking Gear',
            'High-Quality Woodworking Chisels',
            'Premium Herbal Tea Collection',
            'Stylish Laptop Sleeve',
            'Educational Chemistry Kit',
            "Designer Men's Cologne",
            'Fitness Yoga Mat',
            'Sleek Wireless Mouse',
        ];
    }
}
